---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - 
        name: worker
        image: dockersamples/examplevotingapp_worker:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - 
        name: vote
        image: dockersamples/examplevotingapp_vote:latest
        ports:
        -
          containerPort: 8080
          protocol: TCP        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - 
        name: result
        image: dockersamples/examplevotingapp_result:latest
        ports:
        -
          containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - 
        name: redis
        image: redis:latest
        ports:
        -
          containerPort: 6379
          protocol: TCP        
      volumeMounts:
      -
        name: redis
        mountPath: /data
    volumes:
    -
      name: redis
      persistentVolumeClaim:
        claimName: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - 
        name: postgres
        image: postgres:9.4
        ports:
        -
          containerPort: 5432
          protocol: TCP        
---
